#!/usr/bin/env node

import { spawnSync } from "child_process";
import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { extensionData } from "./extensions-data";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const DB_NAME = "api_extensions";

function sqlStr(value: string | null | undefined): string {
  if (value === null || value === undefined) return "NULL";
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlJson(value: unknown): string {
  return sqlStr(JSON.stringify(value));
}

function generateSeedSQL(): string {
  const lines: string[] = [
    "-- Auto-generated seed file for extensions table",
    "-- Generated by: npx tsx src/services/extensions/v1/scripts/seed-db.ts",
    ""
  ];

  for (const ext of extensionData) {
    const iconUrl = ext.icon_url !== undefined ? sqlStr(ext.icon_url) : "NULL";
    lines.push(
      `INSERT OR REPLACE INTO extensions ` +
        `(id, type, name, description, author, releases, website, license, icon_url, readme, source, version, download_url) VALUES (` +
        `${sqlStr(ext.id)}, ${sqlStr(ext.type)}, ${sqlStr(ext.name)}, ${sqlStr(ext.description)}, ` +
        `${sqlJson(ext.author)}, ${sqlJson(ext.releases)}, ${sqlStr(ext.website)}, ` +
        `${sqlJson(ext.license)}, ${iconUrl}, ${sqlStr(ext.readme)}, ` +
        `${sqlJson(ext.source)}, ${sqlStr(ext.version)}, ${sqlStr(ext.download_url)});`
    );
  }

  return lines.join("\n");
}

function runWrangler(args: string[]): void {
  const command = ["wrangler", "d1", "execute", DB_NAME, ...args];
  const result = spawnSync("npx", command, {
    encoding: "utf8",
    stdio: "pipe"
  });

  if (result.error) throw result.error;

  if (result.status !== 0) {
    throw new Error(
      [
        `Wrangler command failed: npx ${command.join(" ")}`,
        result.stderr.trim() ? `stderr: ${result.stderr.trim()}` : "",
        result.stdout.trim() ? `stdout: ${result.stdout.trim()}` : ""
      ]
        .filter(Boolean)
        .join("\n")
    );
  }
}

function seedDatabase(local: boolean): void {
  const schemaPath = join(__dirname, "..", "db", "schema.sql");
  const seedPath = join(__dirname, "..", "db", "seed.sql");
  const localFlag = local ? ["--local"] : [];

  console.log("Generating seed SQL...");
  const seedSQL = generateSeedSQL();
  writeFileSync(seedPath, seedSQL, "utf8");
  console.log(`Seed SQL written to ${seedPath} (${extensionData.length} extensions)`);

  console.log("Applying schema...");
  runWrangler([...localFlag, "--file", schemaPath]);

  console.log("Seeding extensions...");
  runWrangler([...localFlag, "--file", seedPath]);

  console.log("Done.");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const local = !process.argv.includes("--remote");
  try {
    seedDatabase(local);
  } catch (error) {
    console.error(
      `Seed failed: ${error instanceof Error ? error.message : String(error)}`
    );
    process.exit(1);
  }
}

export { seedDatabase };
